### ISSUE TITLE
Botão para recentralizar no mapa android

### ISSUE THREAD

**Issue by andrmacena** [sharetools/zenhub-board#21]

**Comment by LucasIsidoro** [comment]
Para o botão ser visível, alguns critérios são necessários:

- **ShowsUserLocation** deve ser definido **true** porque o padrão é false
- **ShowsMyLocationButton** deve ficar **true**, como é o padrão

**Comment by LucasIsidoro** [comment]
https://github.com/react-native-community/react-native-maps/issues/1033

**Comment by LucasIsidoro** [comment]
https://github.com/react-native-community/react-native-maps/issues/209#issuecomment-350907665
