### ISSUE TITLE
Google Play Services For the Genymotion Emulator

### ISSUE THREAD

**Issue by LucasIsidoro** [sharetools/zenhub-board#30]
For the Genymotion emulator, you can follow these instructions.

https://docs.genymotion.com/Content/03_Virtual_Devices/Emulating_sensors_and_features/OpenGApps.htm

**Comment by marcelo-campos** [comment]
![image](https://user-images.githubusercontent.com/42218230/63630334-fb91c200-c5ef-11e9-8cc6-9b1b4680beec.png)

**Comment by marcelo-campos** [comment]
Google play services working on Genymotion! thanks @LucasIsidoro

**Comment by LucasIsidoro** [comment]
'--' Congratz @marcelo-campos
